/*
Global variables to store the Font Awesome icons
used within the application.
Every entry should have a correspondent variable in
./sass/var/all.scss
*/
Ext.define('Ngcp.csc.icons', {
    statics: {
        adduser: "x-fa fa-user-plus",
        angleleft: "x-fa fa-angle-left",
        angleright: "x-fa fa-angle-right",
        bell: "x-fa fa-bell",
        block: "x-fa fa-ban",
        block2x: "x-fa fa-ban fa-2x",
        book: "x-fa fa-book",
        book2x: "x-fa fa-book fa-2x",
        building: "x-fa fa-building",
        calendar: "x-fa fa-calendar",
        calendar2x: "x-fa fa-calendar fa-2x",
        chevronleft: "x-fa fa-chevron-left",
        chevronight: "x-fa fa-chevron-right",
        check: "x-fa fa-check",
        circle: "x-fa fa-circle",
        cog: "x-fa fa-cog",
        comment: "x-fa fa-comment",
        comment2x: "x-fa fa-comment fa-2x",
        desktop: "x-fa fa-desktop",
        doubleangleright: "x-fa fa-angle-double-right",
        download: "x-fa fa-download",
        download2x: "x-fa fa-download fa-2x",
        edit: "x-fa fa-edit",
        edit2x: "x-fa fa-edit fa-2x",
        envelope: "x-fa fa-envelope",
        envelope2x: "x-fa fa-envelope fa-2x",
        envelope_transparent: "x-fa fa-envelope-o",
        exclamation: "x-fa fa-exclamation",
        fax: "x-fa fa-fax",
        fax2x: "x-fa fa-fax fa-2x",
        faxpaper: "x-fa fa-file-text",
        faxpaper2x: "x-fa fa-file-text fa-2x",
        faxpaper_transparent: "x-fa fa-file-text-o",
        filter: "x-fa fa-filter",
        floppy: "x-fa fa-floppy-o",
        folder: "x-fa fa-folder-open-o",
        home: "x-fa fa-home",
        key: "x-fa fa-key",
        lock: "x-fa fa-lock",
        microphone: "x-fa fa-microphone",
        microphone_slash: "x-fa fa-microphone-slash",
        menu: "x-fa fa-reorder",
        move: "x-fa fa-arrows",
        multichat: "x-fa fa-wechat",
        paintbrush: "x-fa fa-paint-brush",
        pause: "x-fa fa-pause",
        pencil: "x-fa fa-pencil",
        play: "x-fa fa-play",
        play2x: "x-fa fa-play fa-2x",
        phone: "x-fa fa-phone",
        phone2x: "x-fa fa-phone fa-2x",
        phone3x: "x-fa fa-phone fa-3x",
        phone_cancel: "x-fa fa-phone fa-rotate-180",
        phone_cancel2x: "x-fa fa-phone fa-rotate-90 fa-2x",
        phonesquare: "x-fa fa-phone-square",
        send: "x-fa fa-send",
        send2x: "x-fa fa-send fa-2x",
        square: "x-fa fa-square-o",
        square_checked: "x-fa fa-check-square-o",
        star: "x-fa fa-star",
        timescircle: "x-fa fa-times-circle",
        toggle: {
            off: 'x-fa fa-toggle-off',
            off2x: 'x-fa fa-toggle-off fa-2x',
            on: 'x-fa fa-toggle-on',
            on2x: 'x-fa fa-toggle-on fa-2x'
        },
        trash: "x-fa fa-trash",
        trash2x: "x-fa fa-trash fa-2x",
        user: "x-fa fa-user",
        users: "x-fa fa-users",
        user_secret: "x-fa fa-user-secret",
        video: "x-fa fa-video-camera",
        video2x: "x-fa fa-video-camera fa-2x"
    }
})
